# Generated by Django 5.1.2 on 2024-10-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_country_customuser_phone_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
