# Generated by Django 5.1.2 on 2024-10-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_rename_date_course_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='locked',
            field=models.BooleanField(default=True),
        ),
    ]
